#args:
#  - gitcommithash : 0cee220
# ---
version: "3"
services:

  micronaut-consul-bookcatalogue:
    image: "antoniocaccamo/micronaut-consul-bookcatalogue"
    ports:
      - "8080:8080"
    networks: 
      - mn-consul-net

  micronaut-consul-bookinventory:
    image: "antoniocaccamo/micronaut-consul-bookinventory"
    ports:
      - "8081:8081"
    networks: 
      - mn-consul-net

  micronaut-consul-bookrecommandation:
    image: "antoniocaccamo/micronaut-consul-bookrecommandation"
    ports:
      - "8082:8082"
    networks: 
      - mn-consul-net

#  oauth2-resource-server:
##   build: oauth2-resource-server
#    image: "antoniocaccamo/oauth2-resource-server"
#    ports:
#      - "8083:8083"
#    depends_on: 
#      - "oauth2-authorization-server"
#    networks: 
#      - mn-consul-net
#    deploy:
#      replicas: 5
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 300M
#      restart_policy:
#        condition: on-failure

networks: 
    mn-consul-net:



