#args:
#  - gitcommithash : 0cee220
# ---
version: "3"

services:

#  nodeexporter:
#    image: prom/node-exporter
#    container_name: node-exporter
#    ports:
#      - "9100:9100"

#  cadvisor:
#    image: google/cadvisor
#    container_name: cadvisor
#    ports:
#      - "9081:8080"

  consul:
    image: "consul"
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - mn-consul-net

  mongodb:
    image:  bitnami/mongodb
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - mn-consul-net
    volumes:
      - /opt/development/containers/mongodb:/bitnami/mongodb


#  grafana:
#    image: "grafana/grafana"
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - mn-consul-net
#    depends_on: 
#      - prometheus
    

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - $PWD/prometheus:/etc/prometheus
#      - prometheus_data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#    ports:
#      - "9090:9090"
#    networks:
#        - mn-consul-net
#    depends_on: 
#      - consul
#    links: 
#      - consul
      # - bookcatalogue
      # - bookinventory
      # - bookrecommandation

  bookcatalogue:
    image: "antoniocaccamo/micronaut-consul-bookcatalogue"
    container_name: bookcatalogue
    ports:
      - "8080:8080"
    networks: 
      - mn-consul-net
    depends_on:
      - "consul"
      - mongodb
    environment: 
      - CONSUL_HOST=consul
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

  bookinventory:
    image: "antoniocaccamo/micronaut-consul-bookinventory"
    container_name: bookinventory
    ports:
      - "8081:8081"
    networks: 
      - mn-consul-net
    depends_on:
      - "consul"
      - mongodb
    environment: 
      - CONSUL_HOST=consul
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

  bookrecommandation:
    image: "antoniocaccamo/micronaut-consul-bookrecommandation"
    container_name: bookrecommandation
    ports:
      - "8082:8082"
    networks: 
      - mn-consul-net
    depends_on:
      - "consul"
      - mongodb
    environment: 
      - CONSUL_HOST=consul
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

#  oauth2-resource-server:
##   build: oauth2-resource-server
#    image: "antoniocaccamo/oauth2-resource-server"
#    ports:
#      - "8083:8083"
#    depends_on: 
#      - "oauth2-authorization-server"
#    networks: 
#      - mn-consul-net
#    deploy:
#      replicas: 5
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 300M
#      restart_policy:
#        condition: on-failure

networks: 
    mn-consul-net:

#volumes: 
#   mongo_data : {}
#  prometheus_data : {}

