#args:
#  - gitcommithash : 0cee220
# ---
version: "3"
services:

  micronaut-consul:
      image: "consul"
      ports:
        - "8500:8500"
      networks:
        - mn-consul-net


  micronaut-grafana:
      image: "grafana/grafana"
      ports:
        - "3000:3000"
      networks:
        - mn-consul-net

  micronaut-prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
#    volumes:
#      - /opt/prometheus/conf:/etc/prometheus
#      - /opt/prometheus/data:/prometheus
    command:
      - '--config.file=prometheus-micronaut.yml'
#      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
        - mn-consul-net

  micronaut-consul-bookcatalogue:
    image: "antoniocaccamo/micronaut-consul-bookcatalogue"
    ports:
      - "8080:8080"
    networks: 
      - mn-consul-net
    depends_on:
      - "micronaut-consul"
    environment: 
      - CONSUL_HOST=micronaut-consul

  micronaut-consul-bookinventory:
    image: "antoniocaccamo/micronaut-consul-bookinventory"
    ports:
      - "8081:8081"
    networks: 
      - mn-consul-net
    depends_on:
      - "micronaut-consul"
    environment: 
      - CONSUL_HOST=micronaut-consul

  micronaut-consul-bookrecommandation:
    image: "antoniocaccamo/micronaut-consul-bookrecommandation"
    ports:
      - "8082:8082"
    networks: 
      - mn-consul-net
    depends_on:
      - "micronaut-consul"
    environment: 
      - CONSUL_HOST=micronaut-consul

#  oauth2-resource-server:
##   build: oauth2-resource-server
#    image: "antoniocaccamo/oauth2-resource-server"
#    ports:
#      - "8083:8083"
#    depends_on: 
#      - "oauth2-authorization-server"
#    networks: 
#      - mn-consul-net
#    deploy:
#      replicas: 5
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 300M
#      restart_policy:
#        condition: on-failure

networks: 
    mn-consul-net:



